// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCNgjmTO3nsiS_6ZDMYRWMDkOPlrQAWkjo',
    appId: '1:977148777771:web:a0f0edd6c49db3f7c1a16e',
    messagingSenderId: '977148777771',
    projectId: 'chatapp-8e868',
    authDomain: 'chatapp-8e868.firebaseapp.com',
    storageBucket: 'chatapp-8e868.appspot.com',
    measurementId: 'G-Z13004S5ES',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDIESs6ffo8pJwCc_YSfb2WdHNeL8qgEuA',
    appId: '1:977148777771:android:f85e3a8fdb79640bc1a16e',
    messagingSenderId: '977148777771',
    projectId: 'chatapp-8e868',
    storageBucket: 'chatapp-8e868.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDlHaFMrZvs4fZTbIfBdKDepffVggrbWzs',
    appId: '1:977148777771:ios:4a4f3566f9448da0c1a16e',
    messagingSenderId: '977148777771',
    projectId: 'chatapp-8e868',
    storageBucket: 'chatapp-8e868.appspot.com',
    iosClientId: '977148777771-6kkhviki24amljrkpe2ai19i0me5ne4f.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDlHaFMrZvs4fZTbIfBdKDepffVggrbWzs',
    appId: '1:977148777771:ios:4a4f3566f9448da0c1a16e',
    messagingSenderId: '977148777771',
    projectId: 'chatapp-8e868',
    storageBucket: 'chatapp-8e868.appspot.com',
    iosClientId: '977148777771-6kkhviki24amljrkpe2ai19i0me5ne4f.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatapp',
  );
}
